AWSTemplateFormatVersion: 2010-09-09
Description: |

  Kittens Carousel is a static website application deployed on AWS Simple Storage Service (S3), served through Cloudfront and Route 53 using AWS Cloudformation Service.

Parameters:
  DomainName:
    Description: DNS Name of existing Amazon Route 53 hosted zone ex. clarusway.us
    Type: AWS::Route53::HostedZone::Id
  KittensDomainName:
    Description: Full domain name for the App. ex. kittens.clarusway.us
    Type: String
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
Resources:
  KittensBucket:
     Type: "AWS::S3::Bucket"
     Properties:
        AccessControl: PublicRead
        BucketName: !Ref KittensDomainName
        WebsiteConfiguration:
          IndexDocument: index.html
  KittensBucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref KittensBucket #required
      PolicyDocument: #required
        Statement:
        - Sid: PublicReadforStaticWebsite
          Effect: Allow
          Principal: *
          Action: s3:GetObject
          Resource: !Join ['',['arn:aws:s3:::', !Ref 'KittensBucket', /*]]
          # !Sub "${KittenBucket.Arn}/*"
  KittensCertificate:
    Type: "AWS::CertificateManager::Certificate"
    Properties:
      CertificateTransparencyLoggingPreference: ENABLED
      DomainName: !Ref KittensDomainName #required
      DomainValidationOptions:
        - DomainName: !Ref KittensDomainName
          HostedZoneId: !Ref DomainName
      ValidationMethod: DNS
  KittensDNSName:
    Type: "AWS::Route53::RecordSetGroup"
    Properties:
      HostedZoneId: !Ref DomainName
      RecordSets:
        - Name: !Ref KittensDomainName
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: 'put the cloudfront DNS name'
  
  
      
  
Outputs: