AWSTemplateFormatVersion: 2010-09-09

Description: Project-101 - Kittens Carousel Static Website deployed on AWS EC2 using Cloudformation.

Resources:
  E2193CFInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-02354e95b39ca8dec
      InstanceType: t2.micro
      KeyName: aws_key
      SecurityGroups:
        - ssh https http
      Tags:
        - Key: Name
          Value: Project-101
      UserData:    
        Fn::Base64:
          !Sub |
          #! /bin/bash
          yum update -y
          yum install -y httpd
          DATE_TIME=`date`
          cd /var/www/html
          wget https://raw.githubusercontent.com/Gokay2705/Clarusway.AWS.Work.Shop/master/aws/projects/101-kittens-carousel-static-website-ec2/static-web/index.html
          wget https://raw.githubusercontent.com/Gokay2705/Clarusway.AWS.Work.Shop/master/aws/projects/101-kittens-carousel-static-website-ec2/static-web/cat0.jpg
          wget https://raw.githubusercontent.com/Gokay2705/Clarusway.AWS.Work.Shop/master/aws/projects/101-kittens-carousel-static-website-ec2/static-web/cat1.jpg
          wget https://raw.githubusercontent.com/Gokay2705/Clarusway.AWS.Work.Shop/master/aws/projects/101-kittens-carousel-static-website-ec2/static-web/cat2.jpg
          systemctl start httpd
          systemctl enable httpd          