version: "3.7"

services:
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: P12345p
      MYSQL_DATABASE: phonebook_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: Clarusway_1
    volumes:
      - db-data:/var/lib/mysql
      # - ./init.sql:docker-entrypoint-initdb.d/init.sql
    configs:
      - source: initialdatabase
        target: /docker-entrypoint-initdb.d/init.sql  # en iyi cozum bu cunku database nerede kurulacagina grandmaster belirliyor. biz bilmiyoruz.
    networks:
      - clarusnet 
  app-server:
    image: "${ECR_REGISTRY}/${APP_REPO_NAME}:latest"  # .env uzantili dosyadan ismini alir.
    deploy:
      mode: global
      update_config:
        parallelism: 2      # 2 konteyner oldur 5s bekle diger 2 ayaga kaldir.
        delay: 5s           # 5s bekle
        order: start-first  # once olusturdugunu once deploy et.
    ports:
      - "80:80"
    networks:
      - clarusnet 
      
networks:
  clarusnet:
    driver: overlay

volumes:
  db-data:

configs:
  initialdatabase:
    file: ./init.sql